/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package miniprojet_cadenas_gauchet;

/**
 *
 * @author lisagauchet
 */
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import java.util.logging.Level;



public class interface_cadenas extends javax.swing.JFrame {
   
    private metier jeu;
   
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(interface_cadenas.class.getName());

    /**
     * Creates new form Victoire
     */
    public interface_cadenas() {
        initComponents();
        jeu = new metier();
        texte_score.setText(jeu.getTentativesEffectuees() + " sur " + jeu.getMaxTentatives());
        texte_intro.setText("Trouvez le bon code en moins de " + jeu.getMaxTentatives() + " tentatives !");
    }
   
    private void mettreAJourChiffre(javax.swing.JLabel label, boolean increment) {
        if (jeu.estPartieTerminee()) {
            return;
        }
       
        try {
            int chiffre = Integer.parseInt(label.getText());
            if (increment) {
                chiffre = (chiffre + 1) % 10;
            } else {
                chiffre = (chiffre - 1 + 10) % 10;
            }
            label.setText(String.valueOf(chiffre));
        } catch (NumberFormatException e) {
            label.setText("0");
        }
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        texte_intro = new javax.swing.JLabel();
        texte_chiffre_0 = new javax.swing.JLabel();
        texte_chiffre_1 = new javax.swing.JLabel();
        texte_chiffre_2 = new javax.swing.JLabel();
        texte_chiffre_3 = new javax.swing.JLabel();
        texte_lbl_nb_chiffres_exacts = new javax.swing.JLabel();
        texte_nb_chiffres_exacts = new javax.swing.JLabel();
        texte_lbl_nb_chiffres_haut = new javax.swing.JLabel();
        texte_nb_chiffres_haut = new javax.swing.JLabel();
        texte_lbl_nb_chiffres_bas = new javax.swing.JLabel();
        texte_nb_chiffres_bas = new javax.swing.JLabel();
        texte_score = new javax.swing.JLabel();
        texte_tentatives = new javax.swing.JLabel();
        up_chiffre_1 = new javax.swing.JButton();
        up_chiffre_2 = new javax.swing.JButton();
        up_chiffre_3 = new javax.swing.JButton();
        up_chiffre_4 = new javax.swing.JButton();
        down_chiffre_1 = new javax.swing.JButton();
        down_chiffre_2 = new javax.swing.JButton();
        down_chiffre_3 = new javax.swing.JButton();
        down_chiffre_4 = new javax.swing.JButton();
        bouton_tester = new javax.swing.JButton();
        bouton_recommencer = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        texte_intro.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        texte_intro.setForeground(new java.awt.Color(255, 102, 255));
        texte_intro.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        texte_intro.setText("Trouvez le bon code en moins de 5 tentatives !!");
        getContentPane().add(texte_intro, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 30, -1, -1));

        texte_chiffre_0.setFont(new java.awt.Font("Helvetica Neue", 0, 48)); // NOI18N
        texte_chiffre_0.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        texte_chiffre_0.setText("0");
        texte_chiffre_0.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 102, 255)));
        getContentPane().add(texte_chiffre_0, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 140, 72, 140));

        texte_chiffre_1.setFont(new java.awt.Font("Helvetica Neue", 0, 48)); // NOI18N
        texte_chiffre_1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        texte_chiffre_1.setText("0");
        texte_chiffre_1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 102, 255)));
        getContentPane().add(texte_chiffre_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(234, 142, 72, 140));

        texte_chiffre_2.setFont(new java.awt.Font("Helvetica Neue", 0, 48)); // NOI18N
        texte_chiffre_2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        texte_chiffre_2.setText("0");
        texte_chiffre_2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 102, 255)));
        getContentPane().add(texte_chiffre_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(368, 142, 72, 140));

        texte_chiffre_3.setFont(new java.awt.Font("Helvetica Neue", 0, 48)); // NOI18N
        texte_chiffre_3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        texte_chiffre_3.setText("0");
        texte_chiffre_3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 102, 255)));
        getContentPane().add(texte_chiffre_3, new org.netbeans.lib.awtextra.AbsoluteConstraints(492, 146, 72, 131));

        texte_lbl_nb_chiffres_exacts.setForeground(new java.awt.Color(255, 102, 255));
        texte_lbl_nb_chiffres_exacts.setText("Nombre de chiffres exacts:");
        getContentPane().add(texte_lbl_nb_chiffres_exacts, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 360, -1, -1));

        texte_nb_chiffres_exacts.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        texte_nb_chiffres_exacts.setText("0");
        getContentPane().add(texte_nb_chiffres_exacts, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 350, 30, -1));

        texte_lbl_nb_chiffres_haut.setForeground(new java.awt.Color(255, 102, 255));
        texte_lbl_nb_chiffres_haut.setText("Nombre de chiffres trop hauts:");
        getContentPane().add(texte_lbl_nb_chiffres_haut, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 390, -1, -1));

        texte_nb_chiffres_haut.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        texte_nb_chiffres_haut.setText("0");
        getContentPane().add(texte_nb_chiffres_haut, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 380, -1, -1));

        texte_lbl_nb_chiffres_bas.setForeground(new java.awt.Color(255, 102, 255));
        texte_lbl_nb_chiffres_bas.setText("Nombre de chiffres trop bas:");
        getContentPane().add(texte_lbl_nb_chiffres_bas, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 420, -1, -1));

        texte_nb_chiffres_bas.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        texte_nb_chiffres_bas.setText("0");
        getContentPane().add(texte_nb_chiffres_bas, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 420, 20, -1));

        texte_score.setFont(new java.awt.Font("Helvetica Neue", 0, 36)); // NOI18N
        texte_score.setForeground(new java.awt.Color(255, 102, 255));
        texte_score.setText("0 sur 5");
        getContentPane().add(texte_score, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 380, -1, -1));

        texte_tentatives.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        texte_tentatives.setForeground(new java.awt.Color(255, 102, 255));
        texte_tentatives.setText("Tentatives");
        getContentPane().add(texte_tentatives, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 330, -1, 20));

        up_chiffre_1.setForeground(new java.awt.Color(255, 102, 255));
        up_chiffre_1.setText("^");
        up_chiffre_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                up_chiffre_1ActionPerformed(evt);
            }
        });
        getContentPane().add(up_chiffre_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(102, 105, 72, -1));

        up_chiffre_2.setForeground(new java.awt.Color(255, 102, 255));
        up_chiffre_2.setText("^");
        up_chiffre_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                up_chiffre_2ActionPerformed(evt);
            }
        });
        getContentPane().add(up_chiffre_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(234, 105, 72, -1));

        up_chiffre_3.setForeground(new java.awt.Color(255, 102, 255));
        up_chiffre_3.setText("^");
        up_chiffre_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                up_chiffre_3ActionPerformed(evt);
            }
        });
        getContentPane().add(up_chiffre_3, new org.netbeans.lib.awtextra.AbsoluteConstraints(368, 105, 72, -1));

        up_chiffre_4.setForeground(new java.awt.Color(255, 102, 255));
        up_chiffre_4.setText("^");
        up_chiffre_4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                up_chiffre_4ActionPerformed(evt);
            }
        });
        getContentPane().add(up_chiffre_4, new org.netbeans.lib.awtextra.AbsoluteConstraints(492, 105, 72, -1));

        down_chiffre_1.setForeground(new java.awt.Color(255, 102, 255));
        down_chiffre_1.setText("v");
        down_chiffre_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                down_chiffre_1ActionPerformed(evt);
            }
        });
        getContentPane().add(down_chiffre_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(102, 295, 72, -1));

        down_chiffre_2.setForeground(new java.awt.Color(255, 102, 255));
        down_chiffre_2.setText("v");
        down_chiffre_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                down_chiffre_2ActionPerformed(evt);
            }
        });
        getContentPane().add(down_chiffre_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(234, 295, 72, -1));

        down_chiffre_3.setForeground(new java.awt.Color(255, 102, 255));
        down_chiffre_3.setText("v");
        down_chiffre_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                down_chiffre_3ActionPerformed(evt);
            }
        });
        getContentPane().add(down_chiffre_3, new org.netbeans.lib.awtextra.AbsoluteConstraints(368, 295, 72, -1));

        down_chiffre_4.setForeground(new java.awt.Color(255, 102, 255));
        down_chiffre_4.setText("v");
        down_chiffre_4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                down_chiffre_4ActionPerformed(evt);
            }
        });
        getContentPane().add(down_chiffre_4, new org.netbeans.lib.awtextra.AbsoluteConstraints(492, 295, 72, -1));

        bouton_tester.setBackground(new java.awt.Color(255, 102, 255));
        bouton_tester.setText("Tester");
        bouton_tester.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bouton_testerActionPerformed(evt);
            }
        });
        getContentPane().add(bouton_tester, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 210, -1, -1));

        bouton_recommencer.setBackground(new java.awt.Color(255, 102, 255));
        bouton_recommencer.setText("Recommencer");
        bouton_recommencer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bouton_recommencerActionPerformed(evt);
            }
        });
        getContentPane().add(bouton_recommencer, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 450, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void up_chiffre_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_up_chiffre_2ActionPerformed
        mettreAJourChiffre(texte_chiffre_1,true);
    }//GEN-LAST:event_up_chiffre_2ActionPerformed

    private void down_chiffre_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_down_chiffre_3ActionPerformed
        mettreAJourChiffre(texte_chiffre_2,false);
    }//GEN-LAST:event_down_chiffre_3ActionPerformed

    private void bouton_testerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bouton_testerActionPerformed
        if (jeu.estPartieTerminee()) {
            return;
        }

        int[] essai = new int[4];
        try {
            essai[0] = Integer.parseInt(texte_chiffre_0.getText());
            essai[1] = Integer.parseInt(texte_chiffre_1.getText());
            essai[2] = Integer.parseInt(texte_chiffre_2.getText());
            essai[3] = Integer.parseInt(texte_chiffre_3.getText());

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Erreur: Les chiffres ne sont pas au format attendu.", "Erreur", JOptionPane.ERROR_MESSAGE);
            return;
        }

        int[] resultats = jeu.testerCombinaison(essai);
        texte_nb_chiffres_exacts.setText(String.valueOf(resultats[0]));
        texte_nb_chiffres_haut.setText(String.valueOf(resultats[1]));
        texte_nb_chiffres_bas.setText(String.valueOf(resultats[2]));
        texte_score.setText(jeu.getTentativesEffectuees() + " sur " + jeu.getMaxTentatives());

        if (jeu.estPartieTerminee()) {
            bouton_tester.setEnabled(false);
            String message;
            if (jeu.estGagne()) {
                message = "BRAVO !!! Vous avez trouvé le code secret : " + jeu.getCodeSecretString();
            } else {
                message = "PERDU !! Le code secret était : " + jeu.getCodeSecretString();
            }
            JOptionPane.showMessageDialog(this, message, "Fin de partie", JOptionPane.INFORMATION_MESSAGE);
        }

    }//GEN-LAST:event_bouton_testerActionPerformed

    private void up_chiffre_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_up_chiffre_1ActionPerformed
        mettreAJourChiffre(texte_chiffre_0,true);
    }//GEN-LAST:event_up_chiffre_1ActionPerformed

    private void up_chiffre_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_up_chiffre_3ActionPerformed
        mettreAJourChiffre(texte_chiffre_2,true);
    }//GEN-LAST:event_up_chiffre_3ActionPerformed

    private void up_chiffre_4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_up_chiffre_4ActionPerformed
        mettreAJourChiffre(texte_chiffre_3,true);
    }//GEN-LAST:event_up_chiffre_4ActionPerformed

    private void down_chiffre_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_down_chiffre_1ActionPerformed
        mettreAJourChiffre(texte_chiffre_0,false);
    }//GEN-LAST:event_down_chiffre_1ActionPerformed

    private void down_chiffre_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_down_chiffre_2ActionPerformed
        mettreAJourChiffre(texte_chiffre_1,false);
    }//GEN-LAST:event_down_chiffre_2ActionPerformed

    private void down_chiffre_4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_down_chiffre_4ActionPerformed
        mettreAJourChiffre(texte_chiffre_3,false);
    }//GEN-LAST:event_down_chiffre_4ActionPerformed

    private void bouton_recommencerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bouton_recommencerActionPerformed
        jeu.démarrerJeu();

        texte_chiffre_0.setText("0");
        texte_chiffre_1.setText("0");
        texte_chiffre_2.setText("0");
        texte_chiffre_3.setText("0");

        texte_nb_chiffres_exacts.setText("0");
        texte_nb_chiffres_haut.setText("0");
        texte_nb_chiffres_bas.setText("0");

        texte_score.setText(jeu.getTentativesEffectuees() + " sur " + jeu.getMaxTentatives());
       
        bouton_tester.setEnabled(true);
    }//GEN-LAST:event_bouton_recommencerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new interface_cadenas().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bouton_recommencer;
    private javax.swing.JButton bouton_tester;
    private javax.swing.JButton down_chiffre_1;
    private javax.swing.JButton down_chiffre_2;
    private javax.swing.JButton down_chiffre_3;
    private javax.swing.JButton down_chiffre_4;
    private javax.swing.JLabel texte_chiffre_0;
    private javax.swing.JLabel texte_chiffre_1;
    private javax.swing.JLabel texte_chiffre_2;
    private javax.swing.JLabel texte_chiffre_3;
    private javax.swing.JLabel texte_intro;
    private javax.swing.JLabel texte_lbl_nb_chiffres_bas;
    private javax.swing.JLabel texte_lbl_nb_chiffres_exacts;
    private javax.swing.JLabel texte_lbl_nb_chiffres_haut;
    private javax.swing.JLabel texte_nb_chiffres_bas;
    private javax.swing.JLabel texte_nb_chiffres_exacts;
    private javax.swing.JLabel texte_nb_chiffres_haut;
    private javax.swing.JLabel texte_score;
    private javax.swing.JLabel texte_tentatives;
    private javax.swing.JButton up_chiffre_1;
    private javax.swing.JButton up_chiffre_2;
    private javax.swing.JButton up_chiffre_3;
    private javax.swing.JButton up_chiffre_4;
    // End of variables declaration//GEN-END:variables
}
