/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author lisagauchet
 */

public class FenetreQuiz extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FenetreQuiz.class.getName());

    Question[] questions;
    int index= 0;
    int score = 0;
    
    public FenetreQuiz() {
        initComponents();
        questions= new Question[5];
        
        questions[0] = new Question ("Quelle est la capitale de l’Espagne ?", "Lisbonne","Madrid", "Barcelone", "Seville",2);
        questions[1] = new Question("Quel est l’élément chimique dont le symbole est O ?","Or", "Oxygène", "Osmium", "Ozone",2);
        questions[2] = new Question("Combien font 7 × 8 ?","54", "56", "58", "64",2);
        questions[3] = new Question("Quel océan borde la côte ouest de la France ?","Océan Arctique", "Océan Indien", "Océan Atlantique", "Océan Pacifique",3);
        questions[4] = new Question("Quel est le plus grand animal terrestre ?","L’éléphant", "Le rhinocéros", "L’hippopotame", "La girafe",1);
           
        afficherQuestion();
        
    }
    private void repondre (int indexRep) {
        Question q = questions[index];
        
        
        if (indexRep==q.getIndexBonneReponse()) {
            lbl_Feedback.setText("Bonne reponse !");
            score++;
            lblScore.setText("Score :" + score );
        }else{
            lbl_Feedback.setText("Mauvaise réponse dommage");
        }
        
    
}
    private void afficherQuestion() {
    // Si on a fini toutes les questions → afficher score final
        Question q = questions[index];
        lblQuestion.setText(q.getIntitule());
        
        btnRep1.setText(q.getProposition1());
        btnRep2.setText(q.getProposition2());
        btnRep3.setText(q.getProposition3());
        btnRep4.setText(q.getProposition4());
        lbl_Feedback.setText("");
        
        btnRep1.setEnabled(true);
        btnRep2.setEnabled(true);
        btnRep3.setEnabled(true);
        btnRep4.setEnabled(true);
        
        
    }



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblQuestion = new javax.swing.JLabel();
        btnRep1 = new javax.swing.JButton();
        btnRep2 = new javax.swing.JButton();
        btnRep3 = new javax.swing.JButton();
        btnRep4 = new javax.swing.JButton();
        lblScore = new javax.swing.JLabel();
        btnSuivante = new javax.swing.JButton();
        lbl_Feedback = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblQuestion.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        lblQuestion.setForeground(new java.awt.Color(51, 153, 255));
        lblQuestion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblQuestion.setText("lblQuestion");

        btnRep1.setBackground(new java.awt.Color(153, 204, 255));
        btnRep1.setText("btnRep1");
        btnRep1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRep1ActionPerformed(evt);
            }
        });

        btnRep2.setBackground(new java.awt.Color(153, 204, 255));
        btnRep2.setText("btnRep2");
        btnRep2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRep2ActionPerformed(evt);
            }
        });

        btnRep3.setBackground(new java.awt.Color(153, 204, 255));
        btnRep3.setText("btnRep3");
        btnRep3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRep3ActionPerformed(evt);
            }
        });

        btnRep4.setBackground(new java.awt.Color(153, 204, 255));
        btnRep4.setText("btnRep4");
        btnRep4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRep4ActionPerformed(evt);
            }
        });

        lblScore.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        lblScore.setForeground(new java.awt.Color(102, 153, 255));
        lblScore.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblScore.setText("Score");

        btnSuivante.setBackground(new java.awt.Color(153, 204, 255));
        btnSuivante.setText("Question suivante");
        btnSuivante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuivanteActionPerformed(evt);
            }
        });

        lbl_Feedback.setFont(new java.awt.Font("Kailasa", 0, 24)); // NOI18N
        lbl_Feedback.setForeground(new java.awt.Color(51, 153, 255));
        lbl_Feedback.setText("Feeback");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnRep1)
                    .addComponent(btnRep3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnRep2)
                    .addComponent(btnRep4))
                .addGap(116, 116, 116))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(lbl_Feedback)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSuivante))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblQuestion, javax.swing.GroupLayout.PREFERRED_SIZE, 457, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblScore, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_Feedback)
                    .addComponent(btnSuivante))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addComponent(lblQuestion)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRep1)
                    .addComponent(btnRep2))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRep3)
                    .addComponent(btnRep4))
                .addGap(30, 30, 30)
                .addComponent(lblScore)
                .addGap(42, 42, 42))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRep1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRep1ActionPerformed
        repondre(1);
    }//GEN-LAST:event_btnRep1ActionPerformed

    private void btnRep2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRep2ActionPerformed
        repondre(2);
    }//GEN-LAST:event_btnRep2ActionPerformed

    private void btnRep3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRep3ActionPerformed
        repondre(3);
    }//GEN-LAST:event_btnRep3ActionPerformed

    private void btnRep4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRep4ActionPerformed
        repondre(4);
    }//GEN-LAST:event_btnRep4ActionPerformed

    private void btnSuivanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuivanteActionPerformed

        index++;
        if (index >= questions.length) {
            lblQuestion.setText("Fin du Quiz");
            lbl_Feedback.setText("Score final :" + score);
            btnSuivante.setEnabled(false);
        }   else {
            afficherQuestion();
        }
        
    }//GEN-LAST:event_btnSuivanteActionPerformed

    /**
     * @param args the command line arguments
     */
public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    try {
        for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
            if ("Nimbus".equals(info.getName())) {
                javax.swing.UIManager.setLookAndFeel(info.getClassName());
                break;
            }
        }
    } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
        logger.log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>
    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(() -> new FenetreQuiz().setVisible(true));
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRep1;
    private javax.swing.JButton btnRep2;
    private javax.swing.JButton btnRep3;
    private javax.swing.JButton btnRep4;
    private javax.swing.JButton btnSuivante;
    private javax.swing.JLabel lblQuestion;
    private javax.swing.JLabel lblScore;
    private javax.swing.JLabel lbl_Feedback;
    // End of variables declaration//GEN-END:variables

}
