/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Chevauchée_fantastique;

/**
 *
 * @author lisagauchet
 */

import javax.swing.*;
import java.awt.*;

public class FenetreJeu extends JFrame {

    private Plateau Plateau;
    private Cavalier Cavalier;
    private JButton[][] boutons;
    private int taille = 5; // taille du damier

    public FenetreJeu() {
        initialiserNiveau();
        creerInterface();
    }

    private void creerInterface() {
        setTitle("La Chevauchée Fantastique");
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setLayout(new BorderLayout());

        // ---- Damier ----
        JPanel panneauDamier = new JPanel();
        panneauDamier.setLayout(new GridLayout(taille, taille, 2, 2));
        panneauDamier.setBorder(BorderFactory.createEmptyBorder(10, 10, 10, 10));

        boutons = new JButton[taille][taille];

        for (int i = 0; i < taille; i++) {
            for (int j = 0; j < taille; j++) {

                int x = i;
                int y = j;

                boutons[i][j] = new JButton();
                boutons[i][j].setOpaque(true);
                boutons[i][j].setBorderPainted(false);
                boutons[i][j].setPreferredSize(new Dimension(60, 60));

                boutons[i][j].addActionListener(e -> gererClic(x, y));

                panneauDamier.add(boutons[i][j]);
            }
        }

        add(panneauDamier, BorderLayout.CENTER);

        // ---- Boutons de contrôle ----
        JPanel panneauBas = new JPanel();

        JButton btnRestart = new JButton("Recommencer");
        btnRestart.addActionListener(e -> {
            initialiserNiveau();
            rafraichirAffichage();
        });

        JButton btnAide = new JButton("Règles");
        btnAide.addActionListener(e -> {
            JOptionPane.showMessageDialog(this,
                "Déplacez le cavalier comme aux échecs.\n"
              + "Vous ne pouvez aller que sur des cases allumées.\n"
              + "Objectif : éteindre toutes les cases.");
        });

        JButton btnQuitter = new JButton("Quitter");
        btnQuitter.addActionListener(e -> System.exit(0));

        panneauBas.add(btnRestart);
        panneauBas.add(btnAide);
        panneauBas.add(btnQuitter);

        add(panneauBas, BorderLayout.SOUTH);

        rafraichirAffichage();
        pack();
        setLocationRelativeTo(null);
        setVisible(true);
    }

    private void gererClic(int x, int y) {
        if (cavalier.deplacementValide(x, y) && plateau.getCase(x, y).estAllumee()) {
            cavalier.deplacer(x, y);
            plateau.getCase(x, y).eteindre();
            rafraichirAffichage();

            if (plateau.toutesEteintes()) {
                JOptionPane.showMessageDialog(this, "Niveau terminé !");
                chargerNiveauSuivant();
            }
        }
    }

    private void rafraichirAffichage() {
        for (int i = 0; i < taille; i++) {
            for (int j = 0; j < taille; j++) {
                if (cavalier.getX() == i && cavalier.getY() == j) {
                    boutons[i][j].setBackground(Color.BLUE);
                } else if (plateau.getCase(i, j).estAllumee()) {
                    boutons[i][j].setBackground(Color.YELLOW);
                } else {
                    boutons[i][j].setBackground(Color.GRAY);
                }
            }
        }
    }

    private void initialiserNiveau() {
        plateau = new Plateau(taille);

        // Configuration en dur du niveau 1
        boolean[][] config = {
            {true, true, false, false, true},
            {false, true, true, false, false},
            {true, false, true, true, false},
            {false, true, false, true, true},
            {true, false, true, false, true}
        };

        plateau.initialiser(config);
        cavalier = new Cavalier(0, 0); // départ du cavalier
    }

    private void chargerNiveauSuivant() {
        // Pour l’instant on recharge le même niveau
        initialiserNiveau();
        rafraichirAffichage();
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        case1 = new javax.swing.JButton();
        case2 = new javax.swing.JButton();
        case3 = new javax.swing.JButton();
        case4 = new javax.swing.JButton();
        case5 = new javax.swing.JButton();
        case6 = new javax.swing.JButton();
        case7 = new javax.swing.JButton();
        case8 = new javax.swing.JButton();
        case9 = new javax.swing.JButton();
        case10 = new javax.swing.JButton();
        case11 = new javax.swing.JButton();
        case12 = new javax.swing.JButton();
        case13 = new javax.swing.JButton();
        case14 = new javax.swing.JButton();
        case15 = new javax.swing.JButton();
        case16 = new javax.swing.JButton();
        case17 = new javax.swing.JButton();
        case18 = new javax.swing.JButton();
        case19 = new javax.swing.JButton();
        case20 = new javax.swing.JButton();
        case21 = new javax.swing.JButton();
        case22 = new javax.swing.JButton();
        case23 = new javax.swing.JButton();
        case24 = new javax.swing.JButton();
        case25 = new javax.swing.JButton();
        case26 = new javax.swing.JButton();
        case27 = new javax.swing.JButton();
        case28 = new javax.swing.JButton();
        case29 = new javax.swing.JButton();
        case30 = new javax.swing.JButton();
        case31 = new javax.swing.JButton();
        case32 = new javax.swing.JButton();
        case33 = new javax.swing.JButton();
        case34 = new javax.swing.JButton();
        case35 = new javax.swing.JButton();
        case36 = new javax.swing.JButton();
        btn_Recommencer = new javax.swing.JButton();
        btn_quitter = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridLayout(7, 6));

        case1.setBackground(new java.awt.Color(0, 153, 153));
        case1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                case1ActionPerformed(evt);
            }
        });
        getContentPane().add(case1);

        case2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                case2ActionPerformed(evt);
            }
        });
        getContentPane().add(case2);

        case3.setBackground(new java.awt.Color(0, 153, 153));
        getContentPane().add(case3);
        getContentPane().add(case4);

        case5.setBackground(new java.awt.Color(0, 153, 153));
        getContentPane().add(case5);
        getContentPane().add(case6);
        getContentPane().add(case7);

        case8.setBackground(new java.awt.Color(0, 153, 153));
        getContentPane().add(case8);
        getContentPane().add(case9);

        case10.setBackground(new java.awt.Color(0, 153, 153));
        getContentPane().add(case10);

        case11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                case11ActionPerformed(evt);
            }
        });
        getContentPane().add(case11);

        case12.setBackground(new java.awt.Color(0, 153, 153));
        getContentPane().add(case12);

        case13.setBackground(new java.awt.Color(0, 153, 153));
        getContentPane().add(case13);
        getContentPane().add(case14);

        case15.setBackground(new java.awt.Color(0, 153, 153));
        getContentPane().add(case15);
        getContentPane().add(case16);

        case17.setBackground(new java.awt.Color(0, 153, 153));
        case17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                case17ActionPerformed(evt);
            }
        });
        getContentPane().add(case17);
        getContentPane().add(case18);
        getContentPane().add(case19);

        case20.setBackground(new java.awt.Color(0, 153, 153));
        getContentPane().add(case20);

        case21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                case21ActionPerformed(evt);
            }
        });
        getContentPane().add(case21);

        case22.setBackground(new java.awt.Color(0, 153, 153));
        getContentPane().add(case22);
        getContentPane().add(case23);

        case24.setBackground(new java.awt.Color(0, 153, 153));
        getContentPane().add(case24);

        case25.setBackground(new java.awt.Color(0, 153, 153));
        case25.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                case25ActionPerformed(evt);
            }
        });
        getContentPane().add(case25);
        getContentPane().add(case26);

        case27.setBackground(new java.awt.Color(0, 153, 153));
        getContentPane().add(case27);
        getContentPane().add(case28);

        case29.setBackground(new java.awt.Color(0, 153, 153));
        getContentPane().add(case29);
        getContentPane().add(case30);
        getContentPane().add(case31);

        case32.setBackground(new java.awt.Color(0, 153, 153));
        getContentPane().add(case32);
        getContentPane().add(case33);

        case34.setBackground(new java.awt.Color(0, 153, 153));
        getContentPane().add(case34);
        getContentPane().add(case35);

        case36.setBackground(new java.awt.Color(0, 153, 153));
        case36.setForeground(new java.awt.Color(0, 153, 153));
        getContentPane().add(case36);

        btn_Recommencer.setForeground(new java.awt.Color(0, 153, 153));
        btn_Recommencer.setText("Recommencer");
        btn_Recommencer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_RecommencerActionPerformed(evt);
            }
        });
        getContentPane().add(btn_Recommencer);

        btn_quitter.setForeground(new java.awt.Color(0, 153, 153));
        btn_quitter.setText("Quitter");
        btn_quitter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_quitterActionPerformed(evt);
            }
        });
        getContentPane().add(btn_quitter);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_RecommencerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_RecommencerActionPerformed
        btnRestart.addActionListener(e -> {
       initialiserNiveau();      // réinitialise le plateau et le cavalier
       rafraichirAffichage();    // met à jour l’interface graphique
        });
    }//GEN-LAST:event_btn_RecommencerActionPerformed

    private void btn_quitterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_quitterActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btn_quitterActionPerformed

    private void case17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_case17ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_case17ActionPerformed

    private void case21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_case21ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_case21ActionPerformed

    private void case2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_case2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_case2ActionPerformed

    private void case11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_case11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_case11ActionPerformed

    private void case25ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_case25ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_case25ActionPerformed

    private void case1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_case1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_case1ActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Recommencer;
    private javax.swing.JButton btn_quitter;
    private javax.swing.JButton case1;
    private javax.swing.JButton case10;
    private javax.swing.JButton case11;
    private javax.swing.JButton case12;
    private javax.swing.JButton case13;
    private javax.swing.JButton case14;
    private javax.swing.JButton case15;
    private javax.swing.JButton case16;
    private javax.swing.JButton case17;
    private javax.swing.JButton case18;
    private javax.swing.JButton case19;
    private javax.swing.JButton case2;
    private javax.swing.JButton case20;
    private javax.swing.JButton case21;
    private javax.swing.JButton case22;
    private javax.swing.JButton case23;
    private javax.swing.JButton case24;
    private javax.swing.JButton case25;
    private javax.swing.JButton case26;
    private javax.swing.JButton case27;
    private javax.swing.JButton case28;
    private javax.swing.JButton case29;
    private javax.swing.JButton case3;
    private javax.swing.JButton case30;
    private javax.swing.JButton case31;
    private javax.swing.JButton case32;
    private javax.swing.JButton case33;
    private javax.swing.JButton case34;
    private javax.swing.JButton case35;
    private javax.swing.JButton case36;
    private javax.swing.JButton case4;
    private javax.swing.JButton case5;
    private javax.swing.JButton case6;
    private javax.swing.JButton case7;
    private javax.swing.JButton case8;
    private javax.swing.JButton case9;
    // End of variables declaration//GEN-END:variables

