/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package chevauchée_fantastique;
import javax.swing.*;

public class FenetreJeu extends JFrame {
    private Plateau plateau;
    private javax.swing.JButton[][] boutons;

    public FenetreJeu() {
        initComponents();
        initialiserJeu();
}
    private boolean[][] configInitiale() {
    boolean[][] config = new boolean[6][6];
    for (int i = 0; i < 6; i++) {
        for (int j = 0; j < 6; j++) {
            config[i][j] = true;
        }
    }
    return config;
}
    private void initialiserJeu() {
    plateau = new Plateau(6);
    plateau.initialiser(configInitiale()); 
    
    boutons = new javax.swing.JButton[][]{
        {case1, case2, case3, case4, case5, case6},
        {case7, case8, case9, case10, case11, case12},
        {case13, case14, case15, case16, case17, case18},
        {case19, case20, case21, case22, case23, case24},
        {case25, case26, case27, case28, case29, case30},
        {case31, case32, case33, case34, case35, case36}
    };

    // 🔹 ICI on ajoute la boucle 🔹
    for (int i = 0; i < plateau.getTaille(); i++) {
        for (int j = 0; j < plateau.getTaille(); j++) {
            final int x = i;
            final int y = j;
            boutons[i][j].addActionListener(e -> clicCase(x, y));
        }
    }

    mettreAJourAffichage();
}
    private void mettreAJourAffichage() {
    for (int i = 0; i < plateau.getTaille(); i++) {
        for (int j = 0; j < plateau.getTaille(); j++) {

            JButton btn = boutons[i][j];

            if (plateau.getCase(i, j).estAllumee()) {
                btn.setEnabled(true);
                btn.setBackground(new java.awt.Color(0, 153, 153));
            } else {
                btn.setEnabled(false);
                btn.setBackground(java.awt.Color.LIGHT_GRAY);
            }

            if (plateau.getCavalier().getX() == i &&
                plateau.getCavalier().getY() == j) {
                btn.setText("♞");
                btn.setFont(new java.awt.Font("Serif", java.awt.Font.BOLD, 24));
            } else {
                btn.setText("");
            }
        }
    }
}
    private void clicCase(int x, int y) {
    if (plateau.deplacementValide(x, y)) {
        plateau.deplacerCavalier(x, y);
        mettreAJourAffichage();

        if (plateau.victoire()) {
            JOptionPane.showMessageDialog(
                this,
                "Bravo ! Niveau terminé 🎉"
            );
        }
    } else {
        JOptionPane.showMessageDialog(
            this,
            "Déplacement invalide !",
            "Erreur",
            JOptionPane.WARNING_MESSAGE
        );
    }
}

    




    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        case1 = new javax.swing.JButton();
        case2 = new javax.swing.JButton();
        case3 = new javax.swing.JButton();
        case4 = new javax.swing.JButton();
        case5 = new javax.swing.JButton();
        case6 = new javax.swing.JButton();
        case7 = new javax.swing.JButton();
        case8 = new javax.swing.JButton();
        case9 = new javax.swing.JButton();
        case10 = new javax.swing.JButton();
        case11 = new javax.swing.JButton();
        case12 = new javax.swing.JButton();
        case13 = new javax.swing.JButton();
        case14 = new javax.swing.JButton();
        case15 = new javax.swing.JButton();
        case16 = new javax.swing.JButton();
        case17 = new javax.swing.JButton();
        case18 = new javax.swing.JButton();
        case19 = new javax.swing.JButton();
        case20 = new javax.swing.JButton();
        case21 = new javax.swing.JButton();
        case22 = new javax.swing.JButton();
        case23 = new javax.swing.JButton();
        case24 = new javax.swing.JButton();
        case25 = new javax.swing.JButton();
        case26 = new javax.swing.JButton();
        case27 = new javax.swing.JButton();
        case28 = new javax.swing.JButton();
        case29 = new javax.swing.JButton();
        case30 = new javax.swing.JButton();
        case31 = new javax.swing.JButton();
        case32 = new javax.swing.JButton();
        case33 = new javax.swing.JButton();
        case34 = new javax.swing.JButton();
        case35 = new javax.swing.JButton();
        case36 = new javax.swing.JButton();
        btn_Recommencer = new javax.swing.JButton();
        btn_quitter = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridLayout(7, 6));

        case1.setBackground(new java.awt.Color(0, 153, 153));
        getContentPane().add(case1);
        getContentPane().add(case2);

        case3.setBackground(new java.awt.Color(0, 153, 153));
        getContentPane().add(case3);
        getContentPane().add(case4);

        case5.setBackground(new java.awt.Color(0, 153, 153));
        getContentPane().add(case5);
        getContentPane().add(case6);
        getContentPane().add(case7);

        case8.setBackground(new java.awt.Color(0, 153, 153));
        getContentPane().add(case8);
        getContentPane().add(case9);

        case10.setBackground(new java.awt.Color(0, 153, 153));
        getContentPane().add(case10);
        getContentPane().add(case11);

        case12.setBackground(new java.awt.Color(0, 153, 153));
        getContentPane().add(case12);

        case13.setBackground(new java.awt.Color(0, 153, 153));
        getContentPane().add(case13);
        getContentPane().add(case14);

        case15.setBackground(new java.awt.Color(0, 153, 153));
        getContentPane().add(case15);
        getContentPane().add(case16);

        case17.setBackground(new java.awt.Color(0, 153, 153));
        getContentPane().add(case17);
        getContentPane().add(case18);
        getContentPane().add(case19);

        case20.setBackground(new java.awt.Color(0, 153, 153));
        getContentPane().add(case20);
        getContentPane().add(case21);

        case22.setBackground(new java.awt.Color(0, 153, 153));
        getContentPane().add(case22);
        getContentPane().add(case23);

        case24.setBackground(new java.awt.Color(0, 153, 153));
        getContentPane().add(case24);

        case25.setBackground(new java.awt.Color(0, 153, 153));
        getContentPane().add(case25);
        getContentPane().add(case26);

        case27.setBackground(new java.awt.Color(0, 153, 153));
        getContentPane().add(case27);
        getContentPane().add(case28);

        case29.setBackground(new java.awt.Color(0, 153, 153));
        getContentPane().add(case29);
        getContentPane().add(case30);
        getContentPane().add(case31);

        case32.setBackground(new java.awt.Color(0, 153, 153));
        getContentPane().add(case32);
        getContentPane().add(case33);

        case34.setBackground(new java.awt.Color(0, 153, 153));
        getContentPane().add(case34);
        getContentPane().add(case35);

        case36.setBackground(new java.awt.Color(0, 153, 153));
        case36.setForeground(new java.awt.Color(0, 153, 153));
        getContentPane().add(case36);

        btn_Recommencer.setForeground(new java.awt.Color(0, 153, 153));
        btn_Recommencer.setText("Recommencer");
        btn_Recommencer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_RecommencerActionPerformed(evt);
            }
        });
        getContentPane().add(btn_Recommencer);

        btn_quitter.setForeground(new java.awt.Color(0, 153, 153));
        btn_quitter.setText("Quitter");
        btn_quitter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_quitterActionPerformed(evt);
            }
        });
        getContentPane().add(btn_quitter);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_RecommencerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_RecommencerActionPerformed
        initialiserJeu();
    }//GEN-LAST:event_btn_RecommencerActionPerformed

    private void btn_quitterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_quitterActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btn_quitterActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Recommencer;
    private javax.swing.JButton btn_quitter;
    private javax.swing.JButton case1;
    private javax.swing.JButton case10;
    private javax.swing.JButton case11;
    private javax.swing.JButton case12;
    private javax.swing.JButton case13;
    private javax.swing.JButton case14;
    private javax.swing.JButton case15;
    private javax.swing.JButton case16;
    private javax.swing.JButton case17;
    private javax.swing.JButton case18;
    private javax.swing.JButton case19;
    private javax.swing.JButton case2;
    private javax.swing.JButton case20;
    private javax.swing.JButton case21;
    private javax.swing.JButton case22;
    private javax.swing.JButton case23;
    private javax.swing.JButton case24;
    private javax.swing.JButton case25;
    private javax.swing.JButton case26;
    private javax.swing.JButton case27;
    private javax.swing.JButton case28;
    private javax.swing.JButton case29;
    private javax.swing.JButton case3;
    private javax.swing.JButton case30;
    private javax.swing.JButton case31;
    private javax.swing.JButton case32;
    private javax.swing.JButton case33;
    private javax.swing.JButton case34;
    private javax.swing.JButton case35;
    private javax.swing.JButton case36;
    private javax.swing.JButton case4;
    private javax.swing.JButton case5;
    private javax.swing.JButton case6;
    private javax.swing.JButton case7;
    private javax.swing.JButton case8;
    private javax.swing.JButton case9;
    // End of variables declaration//GEN-END:variables
}
